Base of the cross-distro installer, some fixes
The-MoonTg-project/Moon-Userbot pull request #102
Opened 2024-11-26 19:02 UTC by sTiKyt

Fix: Removed some weird characters and slightly improved README.md

Add: Installer asks for root if not provided instead of exiting it

Fix: Installer can determine which package manager it's running with and doesn't have to rely on specific distro

Fix: Installer won't let steps that require "apt" run and will return user to the selection menu, if host distro uses something else (this is a temporary fool-proof solution until the installation steps themselves can be improved to work on different distros)

Fix: Forced users to clearly agree to using default credentials if they don't provide API_ID/HASH, so they don't get banned by mistake and are well aware of the risks

Fix: Made some prompts more clear and easier to understand (At least the ones I was confused with and had to clarify about in chat)

2024-11-27 10:20 UTC, AbhiTheModder requested changes

2024-11-27 10:20 UTC, AbhiTheModder commented on README.md
> +> Ensure you have the git installed
Would be better to add different OS'es installation commands here.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> -  :
The additions were made to confirm that the directory is not merely a placeholder `Moon-Userbot`. Please implement an equivalent or improved conditional.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +source venv/bin/activate
To enhance the setup process, begin by inquiring whether the user wishes to configure the virtual environment before proceeding.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +  read -r -p "Confirmation > " confirmation
This is nice; I liked it.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +# PM PERMIT warn limit is the number of messages a user can receive from others before giving them a warning
It would be better to also mention that the `antipm` plugin needs to be enabled for it to work.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +#Now below is more clear version:
space :>

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +echo "Enter the number of messages others can send you before receiving a warning, and eventually a ban or leave empty for default (3)"
same here, would be better to also mention that the antipm plugin needs to be enabled for it to work.

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +    *)
```suggestion
    3)
```

2024-11-27 10:20 UTC, AbhiTheModder commented on install.sh
> +su -c "python3 install.py ${install_type}" $SUDO_USER || exit 3
The `install_type` is supposed to be set within the `while` loop based on user input, right?

2024-11-27 10:22 UTC, AbhiTheModder commented
@sTiKyt, thank you for the pull request; it's greatly appreciated. Please address the feedback before merging.

2024-11-27 11:40 UTC, AbhiTheModder commented on install.sh
> +#Now below is more clear version:
```suggestion
# Now below is more clear version:
```

2024-11-27 11:42 UTC, AbhiTheModder commented on install.sh
> +# PM PERMIT warn limit is the number of messages a user can receive from others before giving them a warning
```suggestion
# PM PERMIT warn limit is the number of messages a user can receive from others before giving them a warning, requires `antipm` plugin to be enabled
```

2024-11-28 22:55 UTC, sTiKyt commented on install.sh
> -  :
Fixed in 76ecbb925110793255cecdbb9aa0daefe83829b9

2024-11-28 23:00 UTC, sTiKyt commented on install.sh
> +source venv/bin/activate
Adressed in 257db174475db0708c1daabb1926752edc9fe95b

2024-11-28 23:02 UTC, sTiKyt commented on install.sh
> +    *)
Fixed in 722cf0cd76e8bd0374cf3cc456c8b7106159c09a

2024-11-28 23:10 UTC, sTiKyt commented on install.sh
> +su -c "python3 install.py ${install_type}" $SUDO_USER || exit 3
Not sure what you mean, and also not sure what even this "install.py" file for

2024-11-28 23:23 UTC, AbhiTheModder commented on install.sh
> +su -c "python3 install.py ${install_type}" $SUDO_USER || exit 3
> Not sure what you mean, and also not sure what even this "install.py" file for, it seems a bit useless/replaceable with bash in the main file?

variable `install_type` is being used even before it's assigned.

2024-11-29 00:10 UTC, sTiKyt commented on install.sh
> +su -c "python3 install.py ${install_type}" $SUDO_USER || exit 3
Fixed in b891226993c1a6620d589965226fc817a9cdf52e

2024-11-29 00:55 UTC, AbhiTheModder approved these changes

2024-11-29 00:57 UTC, merged